create table if not exists public.classes (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null default '',
  schedule text not null default '',
  school_year text not null default '',
  teacher text not null default '',
  code text not null unique,
  archived boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.class_members (
  class_id bigint not null references public.classes(id) on delete cascade,
  email text not null,
  joined_at timestamptz not null default now(),
  primary key (class_id, email)
);

create index if not exists idx_class_members_email
  on public.class_members (email);

create table if not exists public.quiz_results (
  id bigint generated by default as identity primary key,
  test_type text not null,
  set_number integer not null,
  score integer not null,
  total_questions integer not null default 0,
  answers jsonb,
  created_at timestamptz not null default now(),
  student_email text,
  set_key text
);

create index if not exists idx_quiz_results_created_at
  on public.quiz_results (created_at desc);

create index if not exists idx_quiz_results_student_email
  on public.quiz_results (student_email);

create table if not exists public.topik_sets (
  id bigint generated by default as identity primary key,
  test_type text not null check (test_type in ('listen', 'reading')),
  set_key text not null,
  label text not null,
  audio_url text not null default '',
  display_order integer not null default 9999,
  created_at timestamptz not null default now(),
  unique (test_type, set_key)
);

create table if not exists public.topik_questions (
  id bigint generated by default as identity primary key,
  test_type text not null check (test_type in ('listen', 'reading')),
  set_key text not null,
  question_id integer not null check (question_id > 0),
  type text not null default '',
  content text not null default '',
  options jsonb not null default '[]'::jsonb,
  correct_answer text not null default '1',
  solution text not null default '',
  created_at timestamptz not null default now(),
  unique (test_type, set_key, question_id)
);

create index if not exists idx_topik_sets_type_order
  on public.topik_sets (test_type, display_order, set_key);

create index if not exists idx_topik_questions_set
  on public.topik_questions (test_type, set_key, question_id);
